### ISSUE TITLE
Update header title

### ISSUE THREAD

**Issue by saracope** [saracope/open-gsa#9]
Change wording with logo at top left - to Open Tech (or something better)

**Comment by saracope** [comment]
Possibly GSA Open Technology or GSA Open (since the site is open.gsa.gov).

**Comment by saracope** [comment]
Open GSA?

**Comment by jcastle-zz** [comment]
I am leaning towards GSA Open Technology.  It is more descriptive.  Is it
creative enough?  Descriptive enough?

Joseph R. Castle
Director of GSA Digital Service
GSA IT, Office of the CTO
joseph.castle@gsa.gov
571-259-5843

On Jul 15, 2016, at 7:54 PM, Sara Cope notifications@github.com wrote:

Possible GSA Open Technology or GSA Open (since the site is open.gsa.gov).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/saracope/open-gsa/issues/9#issuecomment-233094539, or mute
the thread
